setting: 
  name: "agri_slam_gs"
  output_root: "./pings_experiments"
  deskew: True
  deskew_ref_ratio: 0.33
  kitti_correct: False
  correct_deg: 0.0
  color_channel: 3
  color_map_on: True 
process:
  min_range_m: 0.5
  max_range_m: 60.0 
  min_z_m: -5.0
  vox_down_m: 0.08
  dynamic_sdf_ratio_thre: 0.5
sampler:
  surface_sample_range_m: 0.3
  surface_sample_n: 4
  free_sample_begin_ratio: 0.3
  free_sample_end_dist_m: 0.8
  free_front_sample_n: 4
  free_behind_sample_n: 1
neuralpoints:
  voxel_size_m: 0.4 # 0.2 # 0.3
  search_alpha: 0.8
  query_nn_k: 8
  feature_dim: 32
  color_feature_dim: 16
  weighted_first: False
decoder:
  freeze_after_frame: 30
  gs_mlp_hidden_dim: 128
loss:
  sigma_sigmoid_m: 0.05
  weight_color: 0.2
  ekional_loss_on: True
  weight_e: 0.1
gs:
  gs_type: gaussian_surfel # select from 3d_gs and gaussian_surfel
  monodepth_on: False # Set to False to avoid dependency issues initially
  exposure_correction_on: True
  affine_exposure_correction: True 
  cam_pose_train_on: False
  eval_cam_refine_on: False
  view_concat_on: True
  dist_concat_on: False
  learn_color_residual: False
  n_gaussian: 8
  gs_iters: 100
  gaussian_bs_ratio: 2.0
  img_pool_size: 60
  long_term_img_pool_size: 120
  short_term_train_prob: 0.6
  gs_down_rate: 1
  gs_vis_down_rate: 1
  gs_keyframe_accu_dist: 1.0 # unit: m
  lambda_depth: 0.01
  lambda_normal_depth: 0.01
  lambda_mono_normal: 0.01
  lambda_opacity: 1e-3 # 5e-4 # increase to have more valid Gaussians
  lambda_area: 1e-2 # 2e-4
  lambda_sky: 1e-3
  consist_shift_count: 0
  lambda_sdf_cons: 0.01
  lambda_sdf_normal_cons: 0.01
  lambda_sdf: 0.5
  unit_scale_ratio: 0.2
  max_scale_ratio: 1.0
  displacement_range_ratio: 2.0
continual:
  batch_size_new_sample: 1000
  pool_capacity: 1e7
  pool_filter_freq: 10
tracker:
  photo_loss: False
  source_vox_down_m: 0.6
  iter_n: 100
pgo:
  map_context: True
  pgo_freq_frame: 30
  context_cosdist: 0.3
  virtual_side_count: 6
  local_loop_dist_thre: 15.0
optimizer:
  batch_size: 8192
  iters: 15
  learning_rate_geo: 2e-3
  learning_rate_color: 2e-3
  learning_rate_exposure: 1e-3
eval:
  mesh_freq_frame: 10 # reconstruct the mesh every x frames
  mesh_min_nn: 19
  sensor_cad_path: ./cad/drone.ply  # Using drone CAD for agricultural robot
